lottery/urls.py
from . import views
from django.urls import path, re_path


urlpatterns = [

    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^faq/$', views.FAQListView.as_view(), name='faq'),
    re_path(r'^contacts/$', views.contacts, name='contacts'),
    re_path(r'^manual/$', views.manual, name='manual'),
    re_path(r'^types/$', views.types, name='types'),
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^user/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user'),
    path('game/<pk>/', views.LotteryDetailView.as_view(), name='game'),

    re_path(r'^login/$', views.steam_login, name='steam_login'),
    re_path(r'^logout/$', views.steam_logout, name='steam_logout'),
    re_path(r'^login/steam/auth/login/callback/$', views.steam_callback, name='steam_callback'),
]

pay4win/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from lottery.sitemaps import StaticViewSitemap, SteamUserSitemap, LotteryGameSitemap


sitemaps = {
    'static': StaticViewSitemap,
    'steamuser': SteamUserSitemap,
    'lotterygame': LotteryGameSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lottery.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lottery/models.py
import math
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from allauth.socialaccount.models import SocialAccount
from django.utils.timezone import now
from bs4 import BeautifulSoup
import requests
import random
from asgiref.sync import sync_to_async


# Жанр
class Genre(models.Model):
    """
    Модель, отвечающая за жанр игр (Например: Экшн, Шутер, Хоррор и т.п.)
    """

    name = models.CharField(max_length=200, help_text='Введите название жанра (Например: Экшн, Шутер, Хоррор и т.п.)')

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


# Вопрос-ответ
class FAQ(models.Model):
    """
    Модель, отвечающая за Частые Вопросы и Ответы на них
    """

    question = models.CharField(max_length=200, help_text='Введите частый вопрос')
    answer = models.TextField(max_length=3000, help_text='Введите краткий и понятный ответ на вопрос')

    def __str__(self):
        return '{0}, {1}'.format(self.question, self.pk)

    class Meta:
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQs'


# Пользователь
class SteamUser(models.Model):
    """
    Модель, отвечающая за Пользователя (в структурированном виде)
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, verbose_name='Пользователь')
    steam_id = models.CharField(max_length=50, verbose_name="steam_id")
    community_visibility_state = models.CharField(max_length=10, verbose_name="Видимость профиля steam")
    profile_state = models.CharField(max_length=10, verbose_name="Имеется ли профиль сообщества steam")
    persona_name = models.CharField(max_length=200, verbose_name="Отображаемое имя пользователя steam")
    profile_url = models.CharField(max_length=200, verbose_name="Ссылка на профиль steam")
    avatar = models.CharField(max_length=400, verbose_name="Автар (маленький размер)")
    avatar_medium = models.CharField(max_length=400, verbose_name="Автар (средний размер)")
    avatar_full = models.CharField(max_length=400, verbose_name="Автар (полный размер)")
    avatar_hash = models.CharField(max_length=256, verbose_name="Хэш сумма аватара")
    last_logoff = models.CharField(max_length=256, verbose_name="Дата последнего онлайна (по юникс)")
    persona_state = models.CharField(max_length=10, verbose_name="Текущий статус пользователя")
    primary_clan_id = models.CharField(max_length=100, verbose_name="ID основного клана пользователя steam")
    time_created = models.CharField(max_length=256, verbose_name="Дата регистрации аккаунта steam (по юникс)")
    persona_state_flags = models.CharField(max_length=10, verbose_name="С чего пользователь онлайн и прочее")

    time_registered = models.DateTimeField(default=now, verbose_name="Дата и время регистрации на Pay4Win")
    time_last_logged_in = models.DateTimeField(null=True, verbose_name="Последняя дата и время входа на Pay4Win")
    lotteries_total_amount = models.IntegerField(default=0, verbose_name="Всего игр сыграно")
    lotteries_gold_amount = models.IntegerField(default=0, verbose_name="Золотых игр сыграно")
    lotteries_silver_amount = models.IntegerField(default=0, verbose_name="Серебряных игр сыграно")
    lotteries_bronze_amount = models.IntegerField(default=0, verbose_name="Бронзовых игр сыграно")
    money_saved = models.IntegerField(default=0, verbose_name="Всего сэкономлено денег (в рублях)")
    lotteries_won_amount = models.IntegerField(default=0, verbose_name="Всего игр выиграно")
    lotteries_lost_amount = models.IntegerField(default=0, verbose_name="Всего игр проиграно")
    lotteries_finished = models.ManyToManyField('LotteryGame', verbose_name="Игры, в которых участвовал пользователь",
                                                related_name="users_finished_lottery", blank=True)
    lotteries_ongoing = models.ManyToManyField('LotteryGame', verbose_name="Игры, в которых участвует пользователь",
                                               related_name="users_ongoing_lottery", blank=True)
    money_current = models.IntegerField(default=0, verbose_name="Текущий баланс")
    profile_is_private = models.BooleanField(default=False, verbose_name="Приватен ли профиль на сервисе?")

    def __str__(self):
        return '{0}) {1}'.format(self.pk, self.persona_name)

    def get_absolute_url(self):
        return reverse('user', args=[str(self.pk)])

    class Meta:
        verbose_name = 'Steam пользователь'
        verbose_name_plural = 'Steam пользователи'
        ordering = ['-pk']


# Функция обновления информации пользователя
def update_user_info(user_to_update, allauth_user_instance):
    user_to_update.steam_id = allauth_user_instance.extra_data['steamid']
    user_to_update.community_visibility_state = allauth_user_instance.extra_data['communityvisibilitystate']
    user_to_update.profile_state = allauth_user_instance.extra_data['profilestate']
    user_to_update.persona_name = allauth_user_instance.extra_data['personaname']
    user_to_update.profile_url = allauth_user_instance.extra_data['profileurl']
    user_to_update.avatar = allauth_user_instance.extra_data['avatar']
    user_to_update.avatar_medium = allauth_user_instance.extra_data['avatarmedium']
    user_to_update.avatar_full = allauth_user_instance.extra_data['avatarfull']
    user_to_update.avatar_hash = allauth_user_instance.extra_data['avatarhash']
    user_to_update.last_logoff = allauth_user_instance.extra_data['lastlogoff']
    user_to_update.persona_state = allauth_user_instance.extra_data['personastate']
    user_to_update.primary_clan_id = allauth_user_instance.extra_data['primaryclanid']
    user_to_update.time_created = allauth_user_instance.extra_data['timecreated']
    user_to_update.persona_state_flags = allauth_user_instance.extra_data['personastateflags']

    user_to_update.time_last_logged_in = now()
    user_to_update.save()


@receiver(post_save, sender=SocialAccount)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        SteamUser.objects.create(user=instance.user)
        new_user = SteamUser.objects.get(user=instance.user)
        update_user_info(new_user, instance)
    else:
        updatable_user = SteamUser.objects.get(user=instance.user)
        update_user_info(updatable_user, instance)


# Игра из Steam и вся информация о ней
class Game(models.Model):
    """
    Модель, отвечающая за всю информацию об игре Steam
    """

    link = models.CharField(max_length=300, unique=True, verbose_name="Ссылка на игру")
    name = models.CharField(max_length=250, unique=True, verbose_name="Название игры steam")
    desc = models.TextField(max_length=550, verbose_name="Описание игры")
    img = models.ImageField(verbose_name="Картинка игры (230x320)")
    genres = models.ManyToManyField(Genre, verbose_name="Жанры игры из стим")
    price = models.IntegerField(verbose_name="Цена игры Steam в рублях")

    class Meta:
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'

    def __str__(self):
        return '{0}'.format(self.name)


# Фото для слайдера игр
class GameSliderPicture(models.Model):
    """
    Модель, отвечающая за фото из Steam для слайдера игр
    """

    game = models.ForeignKey(Game, null=True, on_delete=models.CASCADE, verbose_name='Игра, к которой относятся фото')
    pic_small = models.CharField(max_length=500, verbose_name="Ссылка на маленькую картинку игры")
    pic_medium = models.CharField(max_length=500, verbose_name="Ссылка на среднюю картинку игры")
    pic_large = models.CharField(max_length=500, verbose_name="Ссылка на большую картинку игры")

    class Meta:
        verbose_name = 'Картинка слайдера игр'
        verbose_name_plural = 'Картинки слайдера игр'

    def __str__(self):
        return '{0}'.format(self.game)


# Видео для слайдера игр
class GameSliderVideo(models.Model):
    """
    Модель, отвечающая за видео из Steam для слайдера игр
    """

    game = models.ForeignKey(Game, null=True, on_delete=models.CASCADE, verbose_name='Игра, к которой относится видео')
    preview = models.CharField(max_length=500, verbose_name="Ссылка на превью для видео игры")
    video = models.CharField(max_length=500, verbose_name="Ссылка на видео игры")

    class Meta:
        verbose_name = 'Видео слайдера игр'
        verbose_name_plural = 'Видео слайдера игр'

    def __str__(self):
        return '{0}'.format(self.game)


# Создание новой игры
@receiver(post_save, sender=Game)
def create_game(sender, instance, created, **kwargs):
    # Если мы именно создали новую игру (не просто сохранили)
    if created:
        resp = requests.get(instance.link)
        soup = BeautifulSoup(resp.text, 'lxml')

        # Сначала ищем ссылка на превью для видео
        img_list = soup.select("#highlight_strip .highlight_strip_movie img")
        video_posters_links_list = list(map(lambda x: x['src'], img_list))

        # Теперь ищем ссылки на сами видео
        video_list = soup.select("#highlight_player_area .highlight_movie")
        video_links_list = list(map(lambda x: x['data-webm-source'], video_list))

        # Создаем новые объекты - видео и прикрепляем их к этой игре
        for i in range(len(video_posters_links_list)):
            GameSliderVideo.objects.create(
                game=instance,
                preview=video_posters_links_list[i],
                video=video_links_list[i]
            )

        # Теперь ищем ссылки на миниатюры картинок
        img_list = soup.select("#highlight_strip .highlight_strip_screenshot img")
        img_mini_links_list = list(map(lambda x: x['src'], img_list))

        # Теперь получаем ссылки на средние картинки
        img_medium_links_list = list(map(lambda x: x.replace('116x65', '600x338'), img_mini_links_list))

        # Теперь получаем ссылки на большие картинки

lottery/forms.py
from django import forms


class UserPrivacyForm(forms.Form):
    is_private = forms.BooleanField(label='Сделать профиль приватным', required=False)
    is_private.widget.attrs.update({
        'class': 'form-check-input slf-user-form-check-box',
        'type': 'checkbox',
        'id': 'flexSwitchCheckChecked'
    })


class BuyTicketForm(forms.Form):
    amount = forms.IntegerField(label='Количество', required=True)
    amount.widget.attrs.update({
        'class': 'form-control slf-game-amount-input',
        'type': 'text',
        'id': 'formAmountInput',
        'min': 1,
        'max': 5
    })

lottery/templates/lottery/lotterygame_list.html
{% extends "base_generic.html" %}

{% load static %}

{% block bg_img %}
    style="background-image: url({% static 'img/main_bg.png' %})"
{% endblock %}


{% block links %}
    <link rel="stylesheet" href="{% static 'css/lotterygame_list.css' %}">
    <link rel="stylesheet" href="{% static 'css/libs/ion.rangeSlider.min.css' %}"/>
    <script src="{% static 'js/libs/jquery.min.js' %}"></script>
    <script src="{% static 'js/libs/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'js/lotterygame_list.js' %}"></script>
{% endblock %}

{% block title %}<title>Pay4Win - Поиск розыгрышей</title>{% endblock %}

{% block content %}

    {% if lotterygame_list %}
        <main class="container">
            <form class="input-group mb-3" action="" method="get">

                <div class="slf-search-form-group-1">
                    <div class="slf-search-form-group-1-inner">
                        <input id="slf-search-game-input" type="text" class="form-control" aria-label="Search by game" placeholder="Поиск по названию игры" autocomplete="off">
                        <label for="slf-search-game-input" class="input-group-text slf-search-game-input-loop"><i class="bi bi-search"></i></label>
                    </div>

                    <div class="slf-search-form-group-1-inner-bottom">
                        <select class="form-select slf-search-sort-select" aria-label="Sort select">
                            <option selected>Сортировать</option>
                            <option value="new-to-old">Сначала новые</option>
                            <option value="old-to-new">Сначала старые</option>
                            <option value="exp-to-cheap">По убыванию цены билета</option>
                            <option value="cheap-to-exp">По возрастанию цены билета</option>
                            <option value="empty-to-full">Сначала больше оставшихся билетов</option>
                            <option value="full-to-empty">Сначала больше купленных билетов</option>
                        </select>

                        <div class="slf-search-form-bot">
                            <label class="form-check-label slf-search-form-check" for="flexCheckDefault">
                                Скрывать пустые <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                            </label>
                        </div>
                    </div>
                </div>

                <div class="slf-search-selects-and-slider-wrapper">
                    <div class="slf-search-selects-wrapper">
                        <select class="form-select slf-search-genre-select" aria-label="Genre select">
                            <option selected>По жанру</option>
                            {% if genre_list %}
                                {% for genre in genre_list %}
                                    <option value="{{ genre.pk }}">{{ genre.name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>

                        <select class="form-select slf-search-type-select" aria-label="Type select">
                            <option selected>По типу</option>
                            <option value="Gold">Золото</option>
                            <option value="Silver">Серебро</option>
                            <option value="Bronze">Бронза</option>
                        </select>
                    </div>

                    <div class="slf-search-price-wrapper">
                        <label for="slf-search-price-amount-min" class='slf-search-price-amounts-labels'>Цена от</label>
                        <input id="slf-search-form-price-input-from" type="text" id="slf-search-price-amount-min" class="slf-search-price-amounts" value="{{ min_ticket_price }}" def-price="{{ min_ticket_price }}" autocomplete="off">
                        <input type="text" id="rangePrimary" name="rangePrimary" value="">
                        <label for="slf-search-price-amount-max" class='slf-search-price-amounts-labels'>до</label>
                        <input id="slf-search-form-price-input-to" type="text" id="slf-search-price-amount-max" class="slf-search-price-amounts" value="{{ max_ticket_price }}" def-price="{{ max_ticket_price }}" autocomplete="off">
                    </div>
                </div>

                <button class="btn btn-primary slf-search-form-send" type="submit">Применить</button>
            </form>


            <div id="slfSearchCardHolder" class="slf-card-holder">
                {% for lottery in lotterygame_list %}
                    <div class="slf-lottery-card slf-active-lottery-card  {% if not user.is_authenticated %}slf-lottery-card-user-not-logged-in-small{% endif %} {% if lottery.lottery_type == "g" %}slf-lottery-card-gold{% elif lottery.lottery_type == "s" %}slf-lottery-card-silver{% elif lottery.lottery_type == "b" %}slf-lottery-card-bronze{% endif %}">
                        <img src="{{ lottery.lottery_game_img }}" alt="" class="slf-lottery-card-img">
                        <div class="slf-lottery-card-inner">
                            <div class="slf-lottery-card-info-wrapper">

                                <div class="slf-lottery-card-info-name-wrapper">
                                    <h2 class="slf-lottery-card-name" title="{{ lottery.lottery_game_name }}">{{ lottery.lottery_game_name }}</h2>
                                    <p class="slf-lottery-card-genres">
                                        {% for lottery_genre in lottery.lottery_genres.all %}
                                            {{ lottery_genre }}{% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </p>
                                </div>

                                <div class="slf-lottery-card-lottery-info-wrapper">
                                    <p class="slf-lottery-card-lottery-num">
                                        Игра: <span class="slf-lottery-card-lottery-num-number" title="{{ lottery.id }}">{{ lottery.id }}</span>
                                    </p>
                                    <p class="slf-lottery-card-lottery-type-wrapper">
                                        Тип:
                                        <span class="slf-lottery-card-lottery-type">
                                            {% if lottery.lottery_type == "g" %}
                                                <img class="slf-lottery-card-lottery-type-pic" alt="" src="{% static 'img/lottery-type-gold.png' %}"> Золото
                                            {% elif lottery.lottery_type == "s" %}
                                                <img class="slf-lottery-card-lottery-type-pic" alt="" src="{% static 'img/lottery-type-silver.png' %}"> Серебро
                                            {% elif lottery.lottery_type == "b" %}
                                                <img class="slf-lottery-card-lottery-type-pic" alt="" src="{% static 'img/lottery-type-bronze.png' %}"> Бронза
                                            {% endif %}
                                        </span>
                                    </p>
                                </div>

                                <a class="btn btn-primary slf-lottery-card-participate" href="#">Участвовать</a>
                            </div>

                            <div class="slf-lottery-card-progress">
                                <div class="progress-bar stripes animated slower" style="width: {{ lottery.lottery_progress }}%"></div>
                                <p class="slf-lottery-card-progress-tickets">
                                    {{ lottery.tickets_bought }}/{{ lottery.tickets_amount }}<br><span>БИЛЕТОВ</span>
                                </p>
                            </div>

                            {% if not user.is_authenticated %}
                                <a class="btn btn-primary slf-lottery-card-not-logged-in-btn" href="{% url "steam_login" %}"><img src="{% static 'img/lottery-card-steam-btn.png' %}" alt=""> Войти через STEAM, чтобы играть!</a>
                            {% endif %}

                            <p class="slf-lottery-card-game-desc {% if user.is_authenticated %}slf-lottery-card-game-desc-user-logged-in{% endif %}">
                                {% if user.is_authenticated %}
                                    {{ lottery.lottery_game_desc|truncatechars:480 }}
                                {% else %}
                                    {{ lottery.lottery_game_desc|truncatechars:200 }}
                                {% endif %}
                            </p>

                            <p class="slf-lottery-card-ticket-price {% if user.is_authenticated %}slf-lottery-card-ticket-price-user-logged-in{% endif %}">
                                Цена билета: <strong>{{ lottery.ticket_price }}&#8381;</strong>
                            </p>

                        </div>
                    </div>
                {% endfor %}

                <a id="slfSearchShowMoreBtn" class="btn btn-primary slf-lottery-card-wrapper-load-more-btn" href="#" onclick="showMore(event, this);">Подгрузить ещё</a>
            </div>
        </main>
    {% else %}
        <main class="container">
            <p>В данный момент розыгрышей нету<</p>
        </main>
    {% endif %}

    <script>

        var $range = $("#rangePrimary"),
        $inputFrom = $("#slf-search-form-price-input-from"),
        $inputTo = $("#slf-search-form-price-input-to"),
        instance,
        min = {{ min_ticket_price }},
        max = {{ max_ticket_price }},
        from = {{ min_ticket_price }},
        to = {{ max_ticket_price }};

        $range.ionRangeSlider({
            type: "double",
            min: min,
            max: max,
            from: {{ min_ticket_price }},
            to: {{ max_ticket_price }},
            onStart: updateInputs,
            onChange: updateInputs,
            postfix: "₽"
        });

        instance = $range.data("ionRangeSlider");

        function updateInputs (data) {
            from = data.from;
            to = data.to;

            $inputFrom.prop("value", from);
            $inputTo.prop("value", to);
        }

        $inputFrom.on("input", function () {
            var val = $(this).prop("value");

            // validate
            if (val < min) {
                val = min;
            } else if (val > to) {
                val = to;
            }

            instance.update({
                from: val
            });
        });

        $inputTo.on("input", function () {
            var val = $(this).prop("value");

            // validate
            if (val < from) {
                val = from;
            } else if (val > max) {
                val = max;
            }

            instance.update({
                to: val
            });
        });
    </script>

{% endblock %}

lottery/templates/lottery/search.html
{% extends "base_generic.html" %}

{% load static %}

{% block bg_img %}
    style="background-image: url({% static 'img/main_bg.png' %})"
{% endblock %}


{% block links %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/game_card_open.css' %}">
    <link rel="stylesheet" href="{% static 'css/libs/ion.rangeSlider.min.css' %}"/>
    <script src="{% static 'js/libs/jquery.min.js' %}"></script>
    <script src="{% static 'js/libs/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'js/lottery-number-copy.js' %}"></script>
{% endblock %}

{% block title %}<title>Pay4Win - Поиск розыгрышей</title>{% endblock %}

{% load lotteries_extras %}

{% block content %}

    {% if check_for_games > 0 %}
        <main class="container">
            <form class="input-group mb-3" action="" method="get">

                <div class="slf-search-form-group-1">
                    <div class="slf-search-form-group-1-inner">
                        <input id="slf-search-game-input" type="text" class="form-control" aria-label="Search by game" placeholder="Поиск по названию игры" autocomplete="off" name="search_game_name" value="{% if request.GET.search_game_name %}{{ request.GET.search_game_name }}{% endif %}">
                        <label for="slf-search-game-input" class="input-group-text slf-search-game-input-loop"><i class="bi bi-search"></i></label>
                    </div>

                    <div class="slf-search-form-group-1-inner-bottom">
                        <select class="form-select slf-search-sort-select" aria-label="Sort select" name="search_sort_by">
                            <option value="new-to-old" {% if current_sort %}{% if current_sort == "new-to-old" %}selected{% endif %}{% endif %} {% if not current_sort %}selected{% endif %}>Сначала новые</option>
                            <option value="old-to-new" {% if current_sort %}{% if current_sort == "old-to-new" %}selected{% endif %}{% endif %}>Сначала старые</option>
                            <option value="exp-to-cheap" {% if current_sort %}{% if current_sort == "exp-to-cheap" %}selected{% endif %}{% endif %}>По убыванию цены билета</option>
                            <option value="cheap-to-exp" {% if current_sort %}{% if current_sort == "cheap-to-exp" %}selected{% endif %}{% endif %}>По возрастанию цены билета</option>
                            <option value="empty-to-full" {% if current_sort %}{% if current_sort == "empty-to-full" %}selected{% endif %}{% endif %}>Сначала начинающиеся игры</option>
                            <option value="full-to-empty" {% if current_sort %}{% if current_sort == "full-to-empty" %}selected{% endif %}{% endif %}>Сначала подходящие к концу игры</option>
                        </select>

                        <div class="slf-search-form-bot">
                            <label class="form-check-label slf-search-form-check" for="flexCheckDefault">
                                Скрывать пустые <input class="form-check-input" type="checkbox" value="hide-empty-games" id="flexCheckDefault" name="search_hide_empty" {% if request.GET.search_hide_empty %}checked{% endif %}>
                            </label>
                        </div>
                    </div>
                </div>

                <div class="slf-search-selects-and-slider-wrapper">
                    <div class="slf-search-selects-wrapper">
                        <select class="form-select slf-search-genre-select" aria-label="Genre select" name="search_genre">
                            <option value="" {% if not current_genre %}selected{% endif %}>Любой жанр</option>
                            {% if genre_list %}
                                {% for genre in genre_list %}
                                    <option value="{{ genre.pk }}" {% if current_genre %}{% if current_genre == genre %}selected{% endif %}{% endif %}>{{ genre.name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>

                        <select class="form-select slf-search-type-select" aria-label="Type select" name="search_type">
                            <option value="" {% if not current_type %}selected{% endif %}>Любой тип</option>
                            <option value="Gold" {% if current_type %}{% if current_type == "g" %}selected{% endif %}{% endif %}>Золото</option>
                            <option value="Silver" {% if current_type %}{% if current_type == "s" %}selected{% endif %}{% endif %}>Серебро</option>
                            <option value="Bronze" {% if current_type %}{% if current_type == "b" %}selected{% endif %}{% endif %}>Бронза</option>
                        </select>
                    </div>

                    <div class="slf-search-price-wrapper">
                        <label for="slf-search-price-amount-min" class='slf-search-price-amounts-labels'>Цена от</label>
                        <input id="slf-search-form-price-input-from" type="text" id="slf-search-price-amount-min" class="slf-search-price-amounts" value="{{ min_ticket_price }}" def-price="{{ min_ticket_price }}" autocomplete="off">
                        <input type="text" id="rangePrimary" name="rangePrimary" value="">
                        <label for="slf-search-price-amount-max" class='slf-search-price-amounts-labels'>до</label>
                        <input id="slf-search-form-price-input-to" type="text" id="slf-search-price-amount-max" class="slf-search-price-amounts" value="{{ max_ticket_price }}" def-price="{{ max_ticket_price }}" autocomplete="off">
                    </div>
                </div>

                <button class="btn btn-primary slf-search-form-send" type="submit">Применить</button>
            </form>

            {% if lotterygame_list %}
            <div id="slfSearchCardHolder" class="slf-card-holder">
                {% for lottery in lotterygame_list %}
                    {% include "lottery/game_card_open.html" with lottery=lottery %}
                {% endfor %}

                <a id="slfSearchShowMoreBtn" class="btn btn-primary slf-lottery-card-wrapper-load-more-btn" href="#" onclick="showMore(event, this);">Подгрузить ещё</a>
            </div>
            {% else %}
                <p style="text-align: center">По вашему запросу ничего на найдено. Попробуйте применить другие настройки фильтра или <a href="{% url "search" %}">сбросить фильтр</a></p>
            {% endif %}
        </main>
    {% else %}
        <main class="container">
            <p>В данный момент розыгрышей нету</p>
        </main>
    {% endif %}

    <script>

        var $range = $("#rangePrimary"),
        $inputFrom = $("#slf-search-form-price-input-from"),
        $inputTo = $("#slf-search-form-price-input-to"),
        instance,
        min = {{ min_ticket_price }},
        max = {{ max_ticket_price }},
        from = {% if price_range_min %}{{ price_range_min }} {% else %} {{ min_ticket_price }} {% endif %},
        to = {% if price_range_max %}{{ price_range_max }} {% else %} {{ max_ticket_price }} {% endif %};

        $range.ionRangeSlider({
            type: "double",
            min: min,
            max: max,
            from: {% if price_range_min %}{{ price_range_min }} {% else %} {{ min_ticket_price }} {% endif %},
            to: {% if price_range_max %}{{ price_range_max }} {% else %} {{ max_ticket_price }} {% endif %},
            onStart: updateInputs,
            onChange: updateInputs,
            postfix: "₽"
        });

        instance = $range.data("ionRangeSlider");

        function updateInputs (data) {
            from = data.from;
            to = data.to;

            $inputFrom.prop("value", from);
            $inputTo.prop("value", to);
        }

        $inputFrom.on("input", function () {
            var val = $(this).prop("value");

            // validate
            if (val < min) {
                val = min;
            } else if (val > to) {
                val = to;
            }

            instance.update({
                from: val
            });
        });

        $inputTo.on("input", function () {
            var val = $(this).prop("value");

            // validate
            if (val < from) {
                val = from;
            } else if (val > max) {
                val = max;
            }

            instance.update({
                to: val
            });
        });
    </script>

{% endblock %}